### ISSUE TITLE
randomuser.me doesn't support HTTPS

### ISSUE THREAD

**Issue by dcousens** [touchstonejs/touchstonejs-starter#20]
If using plugins like HTTPS-everywhere, the random user data is not able to be fetched, and therefore gives empty lists throughout.

@arronhunt/@keitharm any ideas to make our lives easier?

**Comment by keitharm** [comment]
We bought an SSL Certificate for our main domain so that credit card details would be safe for people that make donations. And also for potential future features that may require a login or transfer of confidential data.

The API on the other hand is random data that doesn't hold any value so we didn't think it'd be necessary to have HTTPS support for it.

**Comment by keitharm** [comment]
@dcousens Wow, sorry I didn't think of this beforehand...

The "api" subdomain is actually just pointing to randomuser.me/api, so if you need an HTTPS end point, just use: https://randomuser.me/api :)

**Comment by dcousens** [comment]
Resolved in cad576fd63288ce0e4c8031ff6242c779593e426,  thanks @keitharm

**Comment by jossmac** [comment]
This throws an error:
```
XMLHttpRequest cannot load https://randomuser.me/api?nat=au&results=10. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
```

**Comment by keitharm** [comment]
Sorry about that, it should work now :)

**Comment by dcousens** [comment]
Thanks @keitharm ,  closing as this is now resolved as can be seen at https://touchstonejs.github.io/touchstonejs-starter/
