### ISSUE TITLE
Create app archetypes

### ISSUE THREAD

**Issue by jossmac** [touchstonejs/touchstonejs-starter#25]
Apart from the "kitchen sink" app that is the touchstone starter. I think it would be helpful for people if we were to demonstrate an implementation of real-world apps. I suggest:

**Social**
Posts, user details, starring, search, notifications 

**Shop**
Product tiles, product details, simulated in-app purchase, search, reviews

**Photos**
Albums, album details, photo details, selection / deletion

**Messaging**
Message list, message details, searching / removing, sending message

Ping @JedWatson @dcousens thoughts?

**Comment by dcousens** [comment]
I think this would be incredibly useful.

**Comment by jossmac** [comment]
Awesome! Which shall we start with?

**Comment by dcousens** [comment]
IMHO, in order of most familiar to "lots of dev required",  I'd rank them:

* Social
* Messaging
* Shop
* Photos

If we wanted to maximise the diversity of how to use Touchstone,  we'd probably want to go bottom up.   If we wanted to get as much done as quickly as possible,  I'd start top down.

**Comment by LorbusChris** [comment]
Just throwing in a thought on this:
Keystone will need all of those apps as well. 

Maybe it would make sense to develop them together from the ground up? 

This might later also make it easier to port any keystone app to touchstone. It could even pace the way for a ks/ts app  interoperability standard

**Comment by mbrookes** [comment]
What might be more useful initially is an actual bare-bones boilerplate starter app - as @jossmac said, this should really be called "kitchen sink".

**Comment by dcousens** [comment]
@mbrookes so you think we should make *more* repositories?  That sounds like a nightmare to maintain.   Personally I think it'd be fine to just use touchstonejs-starter for these demonstrations.

**Comment by mbrookes** [comment]
@dcousens no, what I'm saying is that there needs to be a starter app with just enough skeleton code to get going, without having to take this kitchen sink demo and strip it down first. Demos are interesting, but a starter app would be more useful initially. 

Think `rails new <name>` or `reapp new <name>` or even just `git clone ...`

touchstonejs-starter is a kitchen-sink demo, not a starter. It's great, but it's misnamed.

**Comment by dcousens** [comment]
@mbrookes in short,  you think we should provide 'templates' as such?

**Comment by JedWatson** [comment]
I agree the repo is misnamed, this is really more `touchstone-demo` (never been a big fan of the term "kitchen sink" personally). Also, it's actually the project we host on the touchstone site _as_ the demo.

:+1: for better ks/ts app interoperability, and the concept of aligned demos.

Probably, instead of a touchstone starter (bare-bones) repo, I think we should go down the generator route. You want the minimum amount of functionality in a generator that's still going to be useful, because they _are_ a lot of overhead to maintain. But it would be a much better way to get up and running.

We use Yeoman for Keystone, I don't mind doing the same here because it gives us the infrastructure out of the box, I'd love a standalone CLI tool as well though if anyone wants to step up and put it together (not hard but I don't have time and would prefer to focus on documentation / guides).

Would be great to put that in touchstone itself so you can run `touchstonejs new <projectname>` and off it goes!

When / if we end up with templates down the track, we could potentially download them from the CLI - imagine something like:

```
$ touchstonejs new my-project
Welcome to TouchstoneJS! We'll create you a new project.
Which template would you like to use?
[x] Blank
[ ] Demo (see demo.touchstonejs.io)
[ ] Social
[ ] Shop
[ ] Photos
[ ] Messaging
Great, we'll create you a new Blank project.
Would you like to create a new directory? [Y/n] Y
Creating my-project...
(npm install)
(cordova install)
You're ready to start!
Type "cd my-project" then "touchstonejs start" to run the development server.
Type "touchstonejs help" for more information, including how to build and deploy your app.
```

**Comment by mbrookes** [comment]
A generator would certainly be ideal. :ok_hand:   - whatever's easiest for for you guys a quick win but that's maintainable.

Really like the cli / templates approach see [ionic getting started](http://ionicframework.com/getting-started/) for similar, but appreciate that's more work, and there are other things you guys are focused on. Can't wait for docs :+1: - part of the reason I'm struggling dissecting the current starter as a relative beginner.

PS. Agree with you on "kitchen sink", I was just using it to reinforce the distinction between demo and starter.

Thanks for all the hard work guys - Touchstone is going to be amazing!
